version: '3'
services:

  # app_quagga:
  #   build: ./Dockerfile
  #   container_name: quagga_cont
  #   ports:
  #     - "3002:3000"

  nginx_btr:
    build:
      context: ./nginx/
    image: nginx/btr_nginx
    container_name: btr_nginx
    ports: 
      - 9001:1001
    # depends_on:
    #   - app_btr
    deploy:
      update_config:
        delay: 10s